services:
  backend:
    container_name: stride_flow_dev_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: stride_flow_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mysql:
    container_name: stride_flow_mysql_dev
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stride_flow
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
       - "3302:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-p1234"]
      interval: 5s
      retries: 10
      timeout: 5s

volumes:
  mysql_data: