# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push-to-ecr:
#     runs-on: ubuntu-latest
#     env:
#       AWS_REGION: eu-north-1
#       ECR_REPO: stride_flow_backend

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build and Push to ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: ${{ env.ECR_REPO }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -f dockerfile.prod -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

#       - name: Execute Remote SSH Commands
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.REMOTE_USER }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           port: 22
#           script: |
#             ${{ secrets.ECR_LOGIN }}
#             cd stride_flow
#             sed -i "s|amazonaws.com/stride_flow_backend:.*|amazonaws.com/stride_flow_backend:${{ github.sha }}|" docker-compose-prod.yaml
#             docker compose -f docker-compose-prod.yaml up -d
            
